# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vig_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(600, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_space = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.input_space.setGeometry(QtCore.QRect(10, 10, 250, 200))
        self.input_space.setObjectName("input_space")
        self.output_space = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.output_space.setGeometry(QtCore.QRect(340, 10, 250, 200))
        self.output_space.setReadOnly(True)
        self.output_space.setObjectName("output_space")
        self.key_space = QtWidgets.QLineEdit(self.centralwidget)
        self.key_space.setGeometry(QtCore.QRect(110, 250, 300, 21))
        self.key_space.setInputMask("")
        self.key_space.setText("")
        self.key_space.setMaxLength(32767)
        self.key_space.setObjectName("key_space")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 210, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 210, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 270, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.set_key = QtWidgets.QPushButton(self.centralwidget)
        self.set_key.setGeometry(QtCore.QRect(420, 250, 75, 23))
        self.set_key.setObjectName("set_key")
        self.code_btn = QtWidgets.QPushButton(self.centralwidget)
        self.code_btn.setGeometry(QtCore.QRect(262, 80, 75, 23))
        self.code_btn.setObjectName("code_btn")
        self.decode_btn = QtWidgets.QPushButton(self.centralwidget)
        self.decode_btn.setGeometry(QtCore.QRect(262, 110, 75, 23))
        self.decode_btn.setObjectName("decode_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Шифратор Виженера"))
        self.label.setText(_translate("MainWindow", "Input"))
        self.label_2.setText(_translate("MainWindow", "Output"))
        self.label_3.setText(_translate("MainWindow", "Key"))
        self.set_key.setText(_translate("MainWindow", "Set key"))
        self.code_btn.setText(_translate("MainWindow", "Code"))
        self.decode_btn.setText(_translate("MainWindow", "Decode"))
